[project]
name = "azure-ai-vision-face-api-mcp-server"
version = "1.0.0"
description = "A Face Detection and Recognition MCP Server to allow the embedding of face attribute detection and face recognition during Agentic AI workflows."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"
dependencies = [
    "azure-ai-vision-face>=1.0.0b2",
    "fastmcp>=2.10.5",
    "openai>=1.97.0",
    "opencv-python>=4.12.0.88",
    "azure-storage-blob>=12.26.0",
    "pytest>=8.4.1"
]

[tool.uv]
package = true

[project.scripts]
azure-face-mcp = "mcpServer:run_server"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
